name: Remove old unused images from registry

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch: # allows for manual invocation

env:
  IMAGE: ${{ secrets.GCP_HOST_GCR }}/${{ secrets.GCP_REGISTRY_PROJECT_ID }}/renaissance

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY_GCR_PUSHER }}

      - uses: 'docker://us-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner-cli'
        with:
          args: >-
            -repo=${{ env.IMAGE }}
            -grace=${{ secrets.INTERVAL_OLD_IMAGES }}
            -keep=10
